apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: cicd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: storage 
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.2.0
    helm:
      values: |-
        defaultBuckets: "airflow, lakehouse"
    chart: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
