apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  namespace: cicd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: "7.3.3"
    chart: "grafana"
    helm:
      values: |-
        admin:
          existingSecret: grafana-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
