apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: cicd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.2.4
    helm:
      values: |-
        volumePermissions:
          enabled: true
        global:
          postgresql:
            auth:
              username: sds8f23c7
              database: airflow
              existingSecret: postgres-secrets
              secretKeys:
                adminPasswordKey: postgres-password
                userPasswordKey: password
                replicationPasswordKey: replication-password
        image:
          debug: true
    chart: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
