apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring  
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitoring"
type: Opaque
data:
  admin-user: "Z3JhZmFuYQo="  
  admin-password: "Z3JhZmFuYWFkbWluCg=="
