apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: storage
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "storage,processing,jupyter"
type: Opaque
data:
  root-user: "bWluaW91c2VyCg=="
  root-password: "bWluaW9zZWNyZXQ="
  
