apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: database
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "database,processing,orchestrator"
type: Opaque
data:
  password: "enN6bHZoM3lzYnNwczJnYno4bXphaXYzOWRsYjA2MHIK"
  postgres-password: "YzA5NzI0ZmYwYjNhN2RlODZiNzMxODU3NTBhMDY2NWI="
  replicationPasswordKey: "MzBrd3Bjc3kweHB1bmZoOWtjd2JkNnhiMTNndWgzYXMK"
